// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srvuoxtmmspuktvvxdpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNydnVveHRtbXNwdWt0dnZ4ZHB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1OTAxOTcsImV4cCI6MjA2NTE2NjE5N30.ItcCd1tM_Y0sQ7YDqKDZZSV5Z4gVWayfnQmdnyBuhsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);