import React from 'react';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Globe } from 'lucide-react';
import { useLanguage } from '@/contexts/LanguageContext';

interface CountrySelectorProps {
  value: string;
  onChange: (value: string) => void;
  required?: boolean;
}

const COUNTRIES = [
  // Afrique (commençant par la RDC)
  { code: 'CD', name: 'Democratic Republic of the Congo', nameFr: 'République Démocratique du Congo (RDC)' },
  { code: 'ZA', name: 'South Africa', nameFr: 'Afrique du Sud' },
  { code: 'DZ', name: 'Algeria', nameFr: 'Algérie' },
  { code: 'AO', name: 'Angola', nameFr: 'Angola' },
  { code: 'BJ', name: 'Benin', nameFr: 'Bénin' },
  { code: 'BW', name: 'Botswana', nameFr: 'Botswana' },
  { code: 'BF', name: 'Burkina Faso', nameFr: 'Burkina Faso' },
  { code: 'BI', name: 'Burundi', nameFr: 'Burundi' },
  { code: 'CM', name: 'Cameroon', nameFr: 'Cameroun' },
  { code: 'CV', name: 'Cape Verde', nameFr: 'Cap-Vert' },
  { code: 'CF', name: 'Central African Republic', nameFr: 'République Centrafricaine' },
  { code: 'TD', name: 'Chad', nameFr: 'Tchad' },
  { code: 'KM', name: 'Comoros', nameFr: 'Comores' },
  { code: 'CG', name: 'Congo', nameFr: 'Congo' },
  { code: 'CI', name: 'Ivory Coast', nameFr: "Côte d'Ivoire" },
  { code: 'DJ', name: 'Djibouti', nameFr: 'Djibouti' },
  { code: 'EG', name: 'Egypt', nameFr: 'Égypte' },
  { code: 'GQ', name: 'Equatorial Guinea', nameFr: 'Guinée Équatoriale' },
  { code: 'ER', name: 'Eritrea', nameFr: 'Érythrée' },
  { code: 'SZ', name: 'Eswatini', nameFr: 'Eswatini' },
  { code: 'ET', name: 'Ethiopia', nameFr: 'Éthiopie' },
  { code: 'GA', name: 'Gabon', nameFr: 'Gabon' },
  { code: 'GM', name: 'Gambia', nameFr: 'Gambie' },
  { code: 'GH', name: 'Ghana', nameFr: 'Ghana' },
  { code: 'GN', name: 'Guinea', nameFr: 'Guinée' },
  { code: 'GW', name: 'Guinea-Bissau', nameFr: 'Guinée-Bissau' },
  { code: 'KE', name: 'Kenya', nameFr: 'Kenya' },
  { code: 'LS', name: 'Lesotho', nameFr: 'Lesotho' },
  { code: 'LR', name: 'Liberia', nameFr: 'Libéria' },
  { code: 'LY', name: 'Libya', nameFr: 'Libye' },
  { code: 'MG', name: 'Madagascar', nameFr: 'Madagascar' },
  { code: 'MW', name: 'Malawi', nameFr: 'Malawi' },
  { code: 'ML', name: 'Mali', nameFr: 'Mali' },
  { code: 'MR', name: 'Mauritania', nameFr: 'Mauritanie' },
  { code: 'MU', name: 'Mauritius', nameFr: 'Maurice' },
  { code: 'MA', name: 'Morocco', nameFr: 'Maroc' },
  { code: 'MZ', name: 'Mozambique', nameFr: 'Mozambique' },
  { code: 'NA', name: 'Namibia', nameFr: 'Namibie' },
  { code: 'NE', name: 'Niger', nameFr: 'Niger' },
  { code: 'NG', name: 'Nigeria', nameFr: 'Nigeria' },
  { code: 'RW', name: 'Rwanda', nameFr: 'Rwanda' },
  { code: 'ST', name: 'Sao Tome and Principe', nameFr: 'Sao Tomé-et-Principe' },
  { code: 'SN', name: 'Senegal', nameFr: 'Sénégal' },
  { code: 'SC', name: 'Seychelles', nameFr: 'Seychelles' },
  { code: 'SL', name: 'Sierra Leone', nameFr: 'Sierra Leone' },
  { code: 'SO', name: 'Somalia', nameFr: 'Somalie' },
  { code: 'SS', name: 'South Sudan', nameFr: 'Soudan du Sud' },
  { code: 'SD', name: 'Sudan', nameFr: 'Soudan' },
  { code: 'TZ', name: 'Tanzania', nameFr: 'Tanzanie' },
  { code: 'TG', name: 'Togo', nameFr: 'Togo' },
  { code: 'TN', name: 'Tunisia', nameFr: 'Tunisie' },
  { code: 'UG', name: 'Uganda', nameFr: 'Ouganda' },
  { code: 'ZM', name: 'Zambia', nameFr: 'Zambie' },
  { code: 'ZW', name: 'Zimbabwe', nameFr: 'Zimbabwe' },
  // Autres pays
  { code: 'AF', name: 'Afghanistan', nameFr: 'Afghanistan' },
  { code: 'AL', name: 'Albania', nameFr: 'Albanie' },
  { code: 'DZ', name: 'Algeria', nameFr: 'Algérie' },
  { code: 'DE', name: 'Germany', nameFr: 'Allemagne' },
  { code: 'AD', name: 'Andorra', nameFr: 'Andorre' },
  { code: 'AO', name: 'Angola', nameFr: 'Angola' },
  { code: 'SA', name: 'Saudi Arabia', nameFr: 'Arabie Saoudite' },
  { code: 'AR', name: 'Argentina', nameFr: 'Argentine' },
  { code: 'AM', name: 'Armenia', nameFr: 'Arménie' },
  { code: 'AU', name: 'Australia', nameFr: 'Australie' },
  { code: 'AT', name: 'Austria', nameFr: 'Autriche' },
  { code: 'AZ', name: 'Azerbaijan', nameFr: 'Azerbaïdjan' },
  { code: 'BS', name: 'Bahamas', nameFr: 'Bahamas' },
  { code: 'BH', name: 'Bahrain', nameFr: 'Bahreïn' },
  { code: 'BD', name: 'Bangladesh', nameFr: 'Bangladesh' },
  { code: 'BB', name: 'Barbados', nameFr: 'Barbade' },
  { code: 'BE', name: 'Belgium', nameFr: 'Belgique' },
  { code: 'BZ', name: 'Belize', nameFr: 'Belize' },
  { code: 'BJ', name: 'Benin', nameFr: 'Bénin' },
  { code: 'BT', name: 'Bhutan', nameFr: 'Bhoutan' },
  { code: 'BY', name: 'Belarus', nameFr: 'Biélorussie' },
  { code: 'BO', name: 'Bolivia', nameFr: 'Bolivie' },
  { code: 'BA', name: 'Bosnia and Herzegovina', nameFr: 'Bosnie-Herzégovine' },
  { code: 'BW', name: 'Botswana', nameFr: 'Botswana' },
  { code: 'BR', name: 'Brazil', nameFr: 'Brésil' },
  { code: 'BN', name: 'Brunei', nameFr: 'Brunei' },
  { code: 'BG', name: 'Bulgaria', nameFr: 'Bulgarie' },
  { code: 'BF', name: 'Burkina Faso', nameFr: 'Burkina Faso' },
  { code: 'BI', name: 'Burundi', nameFr: 'Burundi' },
  { code: 'KH', name: 'Cambodia', nameFr: 'Cambodge' },
  { code: 'CM', name: 'Cameroon', nameFr: 'Cameroun' },
  { code: 'CA', name: 'Canada', nameFr: 'Canada' },
  { code: 'CV', name: 'Cape Verde', nameFr: 'Cap-Vert' },
  { code: 'CL', name: 'Chile', nameFr: 'Chili' },
  { code: 'CN', name: 'China', nameFr: 'Chine' },
  { code: 'CY', name: 'Cyprus', nameFr: 'Chypre' },
  { code: 'CO', name: 'Colombia', nameFr: 'Colombie' },
  { code: 'KM', name: 'Comoros', nameFr: 'Comores' },
  { code: 'CG', name: 'Congo', nameFr: 'Congo' },
  { code: 'KP', name: 'North Korea', nameFr: 'Corée du Nord' },
  { code: 'KR', name: 'South Korea', nameFr: 'Corée du Sud' },
  { code: 'CR', name: 'Costa Rica', nameFr: 'Costa Rica' },
  { code: 'CI', name: 'Ivory Coast', nameFr: "Côte d'Ivoire" },
  { code: 'HR', name: 'Croatia', nameFr: 'Croatie' },
  { code: 'CU', name: 'Cuba', nameFr: 'Cuba' },
  { code: 'DK', name: 'Denmark', nameFr: 'Danemark' },
  { code: 'DJ', name: 'Djibouti', nameFr: 'Djibouti' },
  { code: 'DM', name: 'Dominica', nameFr: 'Dominique' },
  { code: 'EG', name: 'Egypt', nameFr: 'Égypte' },
  { code: 'AE', name: 'United Arab Emirates', nameFr: 'Émirats Arabes Unis' },
  { code: 'EC', name: 'Ecuador', nameFr: 'Équateur' },
  { code: 'ER', name: 'Eritrea', nameFr: 'Érythrée' },
  { code: 'ES', name: 'Spain', nameFr: 'Espagne' },
  { code: 'EE', name: 'Estonia', nameFr: 'Estonie' },
  { code: 'US', name: 'United States', nameFr: 'États-Unis' },
  { code: 'ET', name: 'Ethiopia', nameFr: 'Éthiopie' },
  { code: 'FJ', name: 'Fiji', nameFr: 'Fidji' },
  { code: 'FI', name: 'Finland', nameFr: 'Finlande' },
  { code: 'FR', name: 'France', nameFr: 'France' },
  { code: 'GA', name: 'Gabon', nameFr: 'Gabon' },
  { code: 'GM', name: 'Gambia', nameFr: 'Gambie' },
  { code: 'GE', name: 'Georgia', nameFr: 'Géorgie' },
  { code: 'GH', name: 'Ghana', nameFr: 'Ghana' },
  { code: 'GR', name: 'Greece', nameFr: 'Grèce' },
  { code: 'GD', name: 'Grenada', nameFr: 'Grenade' },
  { code: 'GT', name: 'Guatemala', nameFr: 'Guatemala' },
  { code: 'GN', name: 'Guinea', nameFr: 'Guinée' },
  { code: 'GQ', name: 'Equatorial Guinea', nameFr: 'Guinée Équatoriale' },
  { code: 'GW', name: 'Guinea-Bissau', nameFr: 'Guinée-Bissau' },
  { code: 'GY', name: 'Guyana', nameFr: 'Guyana' },
  { code: 'HT', name: 'Haiti', nameFr: 'Haïti' },
  { code: 'HN', name: 'Honduras', nameFr: 'Honduras' },
  { code: 'HU', name: 'Hungary', nameFr: 'Hongrie' },
  { code: 'IN', name: 'India', nameFr: 'Inde' },
  { code: 'ID', name: 'Indonesia', nameFr: 'Indonésie' },
  { code: 'IQ', name: 'Iraq', nameFr: 'Irak' },
  { code: 'IR', name: 'Iran', nameFr: 'Iran' },
  { code: 'IE', name: 'Ireland', nameFr: 'Irlande' },
  { code: 'IS', name: 'Iceland', nameFr: 'Islande' },
  { code: 'IL', name: 'Israel', nameFr: 'Israël' },
  { code: 'IT', name: 'Italy', nameFr: 'Italie' },
  { code: 'JM', name: 'Jamaica', nameFr: 'Jamaïque' },
  { code: 'JP', name: 'Japan', nameFr: 'Japon' },
  { code: 'JO', name: 'Jordan', nameFr: 'Jordanie' },
  { code: 'KZ', name: 'Kazakhstan', nameFr: 'Kazakhstan' },
  { code: 'KE', name: 'Kenya', nameFr: 'Kenya' },
  { code: 'KG', name: 'Kyrgyzstan', nameFr: 'Kirghizistan' },
  { code: 'KI', name: 'Kiribati', nameFr: 'Kiribati' },
  { code: 'KW', name: 'Kuwait', nameFr: 'Koweït' },
  { code: 'LA', name: 'Laos', nameFr: 'Laos' },
  { code: 'LS', name: 'Lesotho', nameFr: 'Lesotho' },
  { code: 'LV', name: 'Latvia', nameFr: 'Lettonie' },
  { code: 'LB', name: 'Lebanon', nameFr: 'Liban' },
  { code: 'LR', name: 'Liberia', nameFr: 'Libéria' },
  { code: 'LY', name: 'Libya', nameFr: 'Libye' },
  { code: 'LI', name: 'Liechtenstein', nameFr: 'Liechtenstein' },
  { code: 'LT', name: 'Lithuania', nameFr: 'Lituanie' },
  { code: 'LU', name: 'Luxembourg', nameFr: 'Luxembourg' },
  { code: 'MK', name: 'North Macedonia', nameFr: 'Macédoine du Nord' },
  { code: 'MG', name: 'Madagascar', nameFr: 'Madagascar' },
  { code: 'MY', name: 'Malaysia', nameFr: 'Malaisie' },
  { code: 'MW', name: 'Malawi', nameFr: 'Malawi' },
  { code: 'MV', name: 'Maldives', nameFr: 'Maldives' },
  { code: 'ML', name: 'Mali', nameFr: 'Mali' },
  { code: 'MT', name: 'Malta', nameFr: 'Malte' },
  { code: 'MA', name: 'Morocco', nameFr: 'Maroc' },
  { code: 'MH', name: 'Marshall Islands', nameFr: 'Îles Marshall' },
  { code: 'MU', name: 'Mauritius', nameFr: 'Maurice' },
  { code: 'MR', name: 'Mauritania', nameFr: 'Mauritanie' },
  { code: 'MX', name: 'Mexico', nameFr: 'Mexique' },
  { code: 'FM', name: 'Micronesia', nameFr: 'Micronésie' },
  { code: 'MD', name: 'Moldova', nameFr: 'Moldavie' },
  { code: 'MC', name: 'Monaco', nameFr: 'Monaco' },
  { code: 'MN', name: 'Mongolia', nameFr: 'Mongolie' },
  { code: 'ME', name: 'Montenegro', nameFr: 'Monténégro' },
  { code: 'MZ', name: 'Mozambique', nameFr: 'Mozambique' },
  { code: 'MM', name: 'Myanmar', nameFr: 'Myanmar' },
  { code: 'NA', name: 'Namibia', nameFr: 'Namibie' },
  { code: 'NR', name: 'Nauru', nameFr: 'Nauru' },
  { code: 'NP', name: 'Nepal', nameFr: 'Népal' },
  { code: 'NI', name: 'Nicaragua', nameFr: 'Nicaragua' },
  { code: 'NE', name: 'Niger', nameFr: 'Niger' },
  { code: 'NG', name: 'Nigeria', nameFr: 'Nigeria' },
  { code: 'NO', name: 'Norway', nameFr: 'Norvège' },
  { code: 'NZ', name: 'New Zealand', nameFr: 'Nouvelle-Zélande' },
  { code: 'OM', name: 'Oman', nameFr: 'Oman' },
  { code: 'UG', name: 'Uganda', nameFr: 'Ouganda' },
  { code: 'UZ', name: 'Uzbekistan', nameFr: 'Ouzbékistan' },
  { code: 'PK', name: 'Pakistan', nameFr: 'Pakistan' },
  { code: 'PW', name: 'Palau', nameFr: 'Palaos' },
  { code: 'PA', name: 'Panama', nameFr: 'Panama' },
  { code: 'PG', name: 'Papua New Guinea', nameFr: 'Papouasie-Nouvelle-Guinée' },
  { code: 'PY', name: 'Paraguay', nameFr: 'Paraguay' },
  { code: 'NL', name: 'Netherlands', nameFr: 'Pays-Bas' },
  { code: 'PE', name: 'Peru', nameFr: 'Pérou' },
  { code: 'PH', name: 'Philippines', nameFr: 'Philippines' },
  { code: 'PL', name: 'Poland', nameFr: 'Pologne' },
  { code: 'PT', name: 'Portugal', nameFr: 'Portugal' },
  { code: 'QA', name: 'Qatar', nameFr: 'Qatar' },
  { code: 'CF', name: 'Central African Republic', nameFr: 'République Centrafricaine' },
  { code: 'DO', name: 'Dominican Republic', nameFr: 'République Dominicaine' },
  { code: 'CZ', name: 'Czech Republic', nameFr: 'République Tchèque' },
  { code: 'RO', name: 'Romania', nameFr: 'Roumanie' },
  { code: 'GB', name: 'United Kingdom', nameFr: 'Royaume-Uni' },
  { code: 'RU', name: 'Russia', nameFr: 'Russie' },
  { code: 'RW', name: 'Rwanda', nameFr: 'Rwanda' },
  { code: 'KN', name: 'Saint Kitts and Nevis', nameFr: 'Saint-Christophe-et-Niévès' },
  { code: 'SM', name: 'San Marino', nameFr: 'Saint-Marin' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', nameFr: 'Saint-Vincent-et-les-Grenadines' },
  { code: 'LC', name: 'Saint Lucia', nameFr: 'Sainte-Lucie' },
  { code: 'SB', name: 'Solomon Islands', nameFr: 'Îles Salomon' },
  { code: 'SV', name: 'El Salvador', nameFr: 'Salvador' },
  { code: 'WS', name: 'Samoa', nameFr: 'Samoa' },
  { code: 'ST', name: 'Sao Tome and Principe', nameFr: 'Sao Tomé-et-Principe' },
  { code: 'SN', name: 'Senegal', nameFr: 'Sénégal' },
  { code: 'RS', name: 'Serbia', nameFr: 'Serbie' },
  { code: 'SC', name: 'Seychelles', nameFr: 'Seychelles' },
  { code: 'SL', name: 'Sierra Leone', nameFr: 'Sierra Leone' },
  { code: 'SG', name: 'Singapore', nameFr: 'Singapour' },
  { code: 'SK', name: 'Slovakia', nameFr: 'Slovaquie' },
  { code: 'SI', name: 'Slovenia', nameFr: 'Slovénie' },
  { code: 'SO', name: 'Somalia', nameFr: 'Somalie' },
  { code: 'SD', name: 'Sudan', nameFr: 'Soudan' },
  { code: 'SS', name: 'South Sudan', nameFr: 'Soudan du Sud' },
  { code: 'LK', name: 'Sri Lanka', nameFr: 'Sri Lanka' },
  { code: 'SE', name: 'Sweden', nameFr: 'Suède' },
  { code: 'CH', name: 'Switzerland', nameFr: 'Suisse' },
  { code: 'SR', name: 'Suriname', nameFr: 'Suriname' },
  { code: 'SZ', name: 'Eswatini', nameFr: 'Eswatini' },
  { code: 'SY', name: 'Syria', nameFr: 'Syrie' },
  { code: 'TJ', name: 'Tajikistan', nameFr: 'Tadjikistan' },
  { code: 'TZ', name: 'Tanzania', nameFr: 'Tanzanie' },
  { code: 'TD', name: 'Chad', nameFr: 'Tchad' },
  { code: 'TH', name: 'Thailand', nameFr: 'Thaïlande' },
  { code: 'TL', name: 'Timor-Leste', nameFr: 'Timor-Leste' },
  { code: 'TG', name: 'Togo', nameFr: 'Togo' },
  { code: 'TO', name: 'Tonga', nameFr: 'Tonga' },
  { code: 'TT', name: 'Trinidad and Tobago', nameFr: 'Trinité-et-Tobago' },
  { code: 'TN', name: 'Tunisia', nameFr: 'Tunisie' },
  { code: 'TM', name: 'Turkmenistan', nameFr: 'Turkménistan' },
  { code: 'TR', name: 'Turkey', nameFr: 'Turquie' },
  { code: 'TV', name: 'Tuvalu', nameFr: 'Tuvalu' },
  { code: 'UA', name: 'Ukraine', nameFr: 'Ukraine' },
  { code: 'UY', name: 'Uruguay', nameFr: 'Uruguay' },
  { code: 'VU', name: 'Vanuatu', nameFr: 'Vanuatu' },
  { code: 'VA', name: 'Vatican City', nameFr: 'Vatican' },
  { code: 'VE', name: 'Venezuela', nameFr: 'Venezuela' },
  { code: 'VN', name: 'Vietnam', nameFr: 'Vietnam' },
  { code: 'YE', name: 'Yemen', nameFr: 'Yémen' },
  { code: 'ZM', name: 'Zambia', nameFr: 'Zambie' },
  { code: 'ZW', name: 'Zimbabwe', nameFr: 'Zimbabwe' }
];

const CountrySelector: React.FC<CountrySelectorProps> = ({ value, onChange, required = false }) => {
  const { language } = useLanguage();

  const getCountryName = (code: string) => {
    const country = COUNTRIES.find(c => c.code === code);
    if (!country) return code;
    return language === 'fr' ? country.nameFr : country.name;
  };

  return (
    <div className="space-y-2">
      <Label htmlFor="country">
        Pays {required && <span className="text-red-500">*</span>}
      </Label>
      <div className="relative">
        <Select value={value || ''} onValueChange={onChange} required={required}>
          <SelectTrigger className="invitopia-input pl-10">
            <SelectValue placeholder="Sélectionnez un pays">
              {value ? getCountryName(value) : "Sélectionnez un pays"}
            </SelectValue>
          </SelectTrigger>
          <SelectContent className="max-h-60 bg-background">
            {COUNTRIES.map((country) => (
              <SelectItem key={country.code} value={country.code}>
                {language === 'fr' ? country.nameFr : country.name}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        <Globe className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-invitopia-500 pointer-events-none" />
      </div>
    </div>
  );
};

export default CountrySelector;
